FROM centos:7.4.1708

LABEL maintainer="gwf <943242261@qq.com>"
LABEL description="基于 centos 的 nginx 镜像"
LABEL version="1.15.8"

RUN yum -y install wget gcc-c++ pcre pcre-devel zlib zlib-devel openssl openssl-devel \
    && yum clean all

WORKDIR /usr/local/src

ENV NGINX_VERSION 1.15.8
ENV NGINX_EXTRA_CONFIGURE_ARGS --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid
ENV NGINX_LUA_CONFIGURE_ARGS --with-ld-opt="-Wl,-rpath,/usr/local/luajit/lib" --add-module=/usr/local/src/ngx_devel_kit-0.3.1 --add-module=/usr/local/src/lua-nginx-module-0.10.14

ADD *.tar.gz /usr/local/src/
RUN cd luajit2-2.1-20190626 \
    && make PREFIX=/usr/local/luajit \
    && make install PREFIX=/usr/local/luajit \
    && echo -e "export LUAJIT_LIB=/usr/local/luajit/lib\nexport LUAJIT_INC=/usr/local/luajit/include/luajit-2.1" >> /etc/profile \
    && source /etc/profile \
    && cd /usr/local/src \
    && wget http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz \
    && tar -xzvf nginx-$NGINX_VERSION.tar.gz \
    && cd nginx-$NGINX_VERSION \
    && ./configure $NGINX_EXTRA_CONFIGURE_ARGS --with-http_ssl_module $NGINX_LUA_CONFIGURE_ARGS \
    && make && make install \
    && rm -rf /usr/local/src \
    && useradd nginx -s /sbin/nologin -M

EXPOSE 80

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
