FROM centos

LABEL maintainer="gwf <943242261@qq.com>"
LABEL description="基于 centos 的 nginx 镜像"
LABEL version="1.15.12"

RUN yum -y install wget
RUN yum -y install gcc-c++
RUN yum -y install pcre pcre-devel
RUN yum -y install zlib zlib-devel
RUN yum -y install openssl openssl-devel

WORKDIR /usr/local/src

ENV NGINX_VERSION 1.15.12
RUN wget http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz
RUN tar -xzvf nginx-$NGINX_VERSION.tar.gz

WORKDIR nginx-$NGINX_VERSION

ENV NGINX_EXTRA_CONFIGURE_ARGS --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid
RUN ./configure $NGINX_EXTRA_CONFIGURE_ARGS --with-http_ssl_module
RUN make
RUN make install

EXPOSE 80

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
