FROM centos:7.6.1810

LABEL maintainer="gwf <943242261@qq.com>"
LABEL description="基于 centos 的 php 镜像"
LABEL version="7.4.30"

WORKDIR /usr/local/src

ADD libiconv-1.16.tar.gz /usr/local/src/
ADD oniguruma-6.9.6.tar.gz /usr/local/src/
RUN yum -y install wget gcc-c++ make autoconf automake libtool file bison libxml2-devel openssl-devel bzip2-devel curl-devel libpng-devel sqlite-devel \
    && yum clean all \
    && cd libiconv-1.16 \
    && ./configure --prefix=/usr/local/libiconv \
    && make && make install \
    && cd /usr/local/src/oniguruma-6.9.6 \
    && ./autogen.sh \
    && ./configure --prefix=/usr --libdir=/lib64 \
    && make && make install

ENV PHP_VERSION 7.4.30
ENV PHP_INI_DIR /etc/php

# RUN wget https://www.php.net/distributions/php-$PHP_VERSION.tar.bz2
ADD php-$PHP_VERSION.tar.bz2 /usr/local/src/
ADD redis-5.3.7.tgz /usr/local/src/
WORKDIR php-$PHP_VERSION
RUN ./configure --with-config-file-path=$PHP_INI_DIR --with-config-file-scan-dir=$PHP_INI_DIR/conf.d --enable-fpm --enable-bcmath --enable-mbstring --enable-gd --enable-soap --with-openssl --with-zlib --with-bz2 --with-curl --with-gettext --with-iconv=/usr/local/libiconv --with-mysqli --with-pdo-mysql --without-pear --disable-fileinfo \
    && make && make install \
    && mkdir -p $PHP_INI_DIR/conf.d \
    && cp php.ini-* $PHP_INI_DIR/ \
    && cd $PHP_INI_DIR \
    && cp php.ini-production php.ini \
    && cd /usr/local/etc \
    && sed 's!=NONE/!=!g' php-fpm.conf.default | tee php-fpm.conf \
    && cp php-fpm.d/www.conf.default php-fpm.d/www.conf \
    && echo -e '[global]\ndaemonize = no\n[www]\nlisten = 9000' | tee php-fpm.d/zz-docker.conf \
    && cd /usr/local/src/redis-5.3.7 \
    && phpize \
    && ./configure \
    && make && make install \
    && rm -rf /usr/local/src

COPY docker-php-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-php-entrypoint.sh"]

WORKDIR /var/www

STOPSIGNAL SIGQUIT

EXPOSE 9000

CMD ["php-fpm"]
